spring.application.name=Quantity Measurement App
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement_db
spring.datasource.username=root
spring.datasource.password=@rawat2525KHUSHI

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect